### ISSUE TITLE
Make audio only

### ISSUE THREAD

**Issue by ExodowRRGB** [AdamG-13791/TI-Calc-Video-Generator#1]

**Comment by Crazy-Fox-2** [comment]
I'd love to make a version of this that's a dedicated audio player someday. Unfortunately I don't have as much time on my hands as I used to, so it won't be anytime soon.

In the meantime you can check out TruSound: [https://www.ticalc.org/archives/files/fileinfo/433/43319.html](https://www.ticalc.org/archives/files/fileinfo/433/43319.html
).
It doesn't use any audio compression so you're very limited in how much music you can fit on your calculator, but other than that I think it's what you're looking for.
